### ISSUE TITLE
求助，谢谢楼主！

### ISSUE THREAD

**Issue by haoyuzh** [yipeipei/query-gre-seats#4]
你好 我用过Python3.4.3和Python3.5.3分别运行的这个程序，都出现了以下问题。。。不知道该怎么办
谢谢楼主分享的软件！感谢！
Traceback (most recent call last):
  File "query-gre-seats.py", line 188, in <module>
    main()
  File "query-gre-seats.py", line 177, in main
    start_query()
  File "query-gre-seats.py", line 152, in start_query
    data = json.loads(echo)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by yipeipei** [comment]
这个程序自 2016 年 7 月不能用了。

> 2016-07-04: NEEA employs new technology to prevent automatically querying. This script does not work any more until update.

希望你能考个好成绩！

**Comment by haoyuzh** [comment]
好的 还是谢谢了！
现在可以去淘宝上买那种代刷考位的服务，如果有人问你的话 可以跟他说一声！

发自我的 iPhone

> 在 2018年6月24日，14:46，YI Peipei <notifications@github.com> 写道：
> 
> 这个程序自 2017 年 7 月不能用了。
> 
> > 2016-07-04: NEEA employs new technology to prevent automatically querying. This script does not work any more until update.
> 
> 希望你能考个好成绩！
>

**Comment by yipeipei** [comment]
OK. 多谢

**Comment by pjpjq** [comment]
@haoyuzh 
 请问有推荐的代报吗
